In [3]:
import numpy as np
from scipy.spatial.transform import Rotation as R


In [25]:
a = np.array([1,2,3])
b = np.array([1,2,3])

In [26]:
a+b

array([2, 4, 6])

In [27]:
c  = a + b
c

array([2, 4, 6])

In [28]:
c = a - b
c

array([0, 0, 0])

In [30]:
c = a*b
c

array([1, 4, 9])

In [32]:
c = a/b
c

array([1., 1., 1.])

In [34]:
a.dot(b)

14

In [35]:
np.dot(a,b)

14

In [36]:
d = np.array([1,2,3,4])

In [37]:
np.dot(a,d)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [38]:
3*b

array([3, 6, 9])

In [41]:
a.T

array([1, 2, 3])

In [43]:
a*b.T

array([1, 4, 9])

In [48]:
A = np.array([[1,2,3]])
B = np.array([[1,2,3]])

In [49]:
A

array([[1, 2, 3]])

In [50]:
A.T

array([[1],
       [2],
       [3]])

In [52]:
A*B.T

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])