<a href="https://colab.research.google.com/github/AltamarMx/ai_fluidmechanics/blob/main/complementary_material/erm_001_rotations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from scipy.spatial.transform import Rotation as R
import ipywidgets as widgets
from ipywidgets import interact

In [7]:
r = R.from_euler('x',90,degrees=True)
r.as_matrix().round(3)

array([[ 1.,  0.,  0.],
       [ 0.,  0., -1.],
       [ 0.,  1.,  0.]])

In [8]:
r = R.from_euler('y',90,degrees=True)
r.as_matrix().round(3)

array([[ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [-1.,  0.,  0.]])

In [9]:
r = R.from_euler('z',90,degrees=True)
r.as_matrix().round(3)

array([[ 0., -1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.]])

In [10]:
r = R.from_euler("xyz",[90,45,0],degrees=True)
r.as_matrix().round(3)

array([[ 0.707,  0.707,  0.   ],
       [ 0.   ,  0.   , -1.   ],
       [-0.707,  0.707,  0.   ]])

In [11]:
r = R.from_euler("yzx",[45,0,90],degrees=True)
r.as_matrix().round(3)

array([[ 0.707,  0.   ,  0.707],
       [ 0.707,  0.   , -0.707],
       [-0.   ,  1.   ,  0.   ]])

In [13]:
thetax = 0
thetay = 0
thetaz = 30
p = np.array([np.sqrt(3),1,0])
r = R.from_euler('xyz',[thetax,thetay,thetaz],degrees=True)
r.as_matrix().round(2)

array([[ 0.87, -0.5 ,  0.  ],
       [ 0.5 ,  0.87,  0.  ],
       [ 0.  ,  0.  ,  1.  ]])

In [14]:
s = r.inv()
s.as_matrix().round()

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [16]:
s.apply(p).round()

array([2., 0., 0.])

In [17]:

elev = 30
azim = 60
thetax, thetay, thetaz = 10,20,30


def rotation(thetax=0,thetay=0,thetaz=0):
    elev=30
    azim=60
    vx = np.array([1,0,0])
    vy = np.array([0,1,0])
    vz = np.array([0,0,1])
    o  = np.array([0,0,0])
    p = np.array([3**.5,1,0])
                 
    r = R.from_euler('xyz',[thetax,thetay,thetaz],degrees=True)
                 
    vx_r = r.apply(vx)
    vy_r = r.apply(vy)
    vz_r = r.apply(vz)

    fig = plt.figure()
#     ax = Axes3D(fig,auto_add_to_figure=False)
    ax = Axes3D(fig)
#     fig.add_axes(ax)
    ax.quiver3D(o[0],o[1],o[2], vx[0],vx[1],vx[2] ,color="blue", label="x" ,linestyle="dashed")
    ax.quiver3D(o[0],o[1],o[2], vy[0],vy[1],vy[2] ,color="red",  label="y" ,linestyle="dashed")
    ax.quiver3D(o[0],o[1],o[2], vz[0],vz[1],vz[2] ,color="green",label="z" ,linestyle="dashed")


    ax.quiver3D(o[0],o[1],o[2], vx_r[0],vx_r[1],vx_r[2] ,color="blue", label="x'")
    ax.quiver3D(o[0],o[1],o[2], vy_r[0],vy_r[1],vy_r[2] ,color="red",  label="y'")
    ax.quiver3D(o[0],o[1],o[2], vz_r[0],vz_r[1],vz_r[2] ,color="green",label="z'")

    
    
#     thetaz_r = thetaz *np.pi/180.
#     mr = np.array([[np.cos(thetaz_r), -np.sin(thetaz_r)],
#                    [np.sin(thetaz_r),  np.cos(thetaz_r)]])
    mri = r.inv()
    pr = mri.apply(p)
    print('Matriz de rotación:\n')
    print(r.as_matrix().round(3))
    print('\n')
    
    print("x  = ",p.round(3))
    print("x' = ",pr.round(3))
                 
    ax.scatter(p[0],p[1],p[2],color='k')
                 
    ax.set_xlim(-2,2)
    ax.set_ylim(-2,2)
    ax.set_zlim(-2,2)
    ax.legend()
    ax.view_init(elev,azim)

In [18]:
interactive_rotation = interact(rotation,
         angle=widgets.IntSlider(min=0,max=360,    step=15,value=0),
         thetax=widgets.IntSlider(min=-180,max=180,step=15,value=0),
         thetay=widgets.IntSlider(min=-180,max=180,step=15,value=0),
         thetaz=widgets.IntSlider(min=-180,max=180,step=15,value=0),
         );

interactive(children=(IntSlider(value=0, description='thetax', max=180, min=-180, step=15), IntSlider(value=0,…